export const onboarding_bgs = ["#A5BBFF", "#DDBEFE", "#FF63ED", "#B98EFF"];

export const onboarding_list = [
  {
    key: "preferences",
    title: "Who Would You Like to Meet?",
    description: "Share your preferences so we can find your best matches.",
    image: "https://cdn-icons-png.flaticon.com/256/3571/3571572.png",
    type: "preference",
    options: [
      { id: "women", label: "Women" },
      { id: "men", label: "Men" },
      { id: "both", label: "Both" },
    ],
  },
  {
    key: "profile",
    title: "Introduce Yourself",
    description: "Share your name so others can get to know you.",
    image: "https://cdn-icons-png.flaticon.com/256/3571/3571747.png",
    type: "name",
    placeholder: "Your Name",
  },
  {
    key: "zodiac",
    title: "Zodiac Compatibility",
    description: "Select your zodiac sign for astrological matches.",
    image: "https://cdn-icons-png.flaticon.com/256/3571/3571680.png",
    type: "zodiac",
    options: [
      "Aries",
      "Taurus",
      "Gemini",
      "Cancer",
      "Leo",
      "Virgo",
      "Libra",
      "Scorpio",
      "Sagittarius",
      "Capricorn",
      "Aquarius",
      "Pisces",
    ],
  },
  {
    key: "interests",
    title: "Your Interests",
    description:
      "Choose your interests to match with people who share your passions.",
    image: "https://cdn-icons-png.flaticon.com/256/3571/3571603.png",
    type: "interests",
    options: [
      "Music",
      "Sports",
      "Travel",
      "Art",
      "Movies/TV",
      "Books",
      "Food",
      "Photography",
      "Dance",
      "Yoga",
      "Nature",
      "Technology",
    ],
  },
];
